# Generated by Django 3.1.7 on 2021-07-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subtoatal',
            new_name='subtotal',
        ),
    ]
