# Generated by Django 3.1.7 on 2021-07-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0002_auto_20210722_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totl',
            new_name='total',
        ),
    ]
